# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    CORENAME: fixgb
    MAKEFILE_PATH: libretro
    MAKEFILE: Makefile
  
# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'

  # Windows 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-i686-mingw.yml'

  # Linux 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-i686.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'

  # MacOS 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-x64.yml'

  # MacOS ARM 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-arm64.yml'

  ################################## CELLULAR ################################
  # iOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios-arm64.yml'

  # iOS (armv7)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios9.yml'
    
  ################################## CONSOLES ################################
  # Nintendo GameCube
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ngc-static.yml'

  # Nintendo Wii
  - project: 'libretro-infrastructure/ci-templates'
    file: '/wii-static.yml'

  # Nintendo WiiU
  - project: 'libretro-infrastructure/ci-templates'
    file: '/wiiu-static.yml'

  # tvOS (AppleTV)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/tvos-arm64.yml'

  #################################### MISC ##################################

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs

# Windows 32-bit
libretro-build-windows-i686:
  extends:
    - .libretro-windows-i686-mingw-make-default
    - .core-defs

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs

# Linux 32-bit
libretro-build-linux-i686:
  extends:
    - .libretro-linux-i686-make-default
    - .core-defs

# MacOS 64-bit
libretro-build-osx-x64:
  extends:
    - .libretro-osx-x64-make-default
    - .core-defs

# MacOS ARM 64-bit
libretro-build-osx-arm64:
  extends:
    - .libretro-osx-arm64-make-default
    - .core-defs

################################### CELLULAR #################################

# iOS
libretro-build-ios-arm64:
  extends:
    - .libretro-ios-arm64-make-default
    - .core-defs

# iOS (armv7) [iOS 9 and up]
libretro-build-ios9:
  extends:
    - .libretro-ios9-make-default
    - .core-defs
    
# tvOS
libretro-build-tvos-arm64:
  extends:
    - .libretro-tvos-arm64-make-default
    - .core-defs
    
################################### CONSOLES #################################
# Nintendo GameCube
libretro-build-ngc:
  extends:
    - .libretro-ngc-static-retroarch-master
    - .core-defs

# Nintendo Wii
libretro-build-wii:
  extends:
    - .libretro-wii-static-retroarch-master
    - .core-defs

# Nintendo WiiU
libretro-build-wiiu:
  extends:
    - .libretro-wiiu-static-retroarch-master
    - .core-defs
